services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mxgo-php
    container_name: mxgo-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    networks:
      - mxgo-network

  webserver:
    image: nginx:alpine
    container_name: mxgo-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - mxgo-network

networks:
  mxgo-network:
    driver: bridge
